### ISSUE TITLE
Container doesn't start due to missing run.py

### ISSUE THREAD

**Issue by walzph** [ghga-de/sandbox-ui#21]
```
Error: failed to start container "sandbox-ui": Error response from daemon: OCI runtime create failed: 
container_linux.go:367: starting container process caused: 
exec: "/service/configure_build_serve/run.py": 
stat /service/configure_build_serve/run.py: no such file or directory: unknown
```

**Comment by deepakunni3** [comment]
Looks like the container deploys locally without issues.

Based on the error message above, the container can't seem to find `/service/configure_build_serve/run.py` even though the Dockerfile `WORKDIR` is `/service`.

**Comment by deepakunni3** [comment]
After discussing with @walzph , this bug was due to the `/service` folder being overwritten when the config YAML was injected.

Fixed via https://github.com/ghga-de/sandbox-ui/pull/22
